name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # run daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: qgeng1465
          gif_out_path: github-contribution-snake/github-contribution-grid-snake.gif
          svg_out_path: github-contribution-snake/github-contribution-grid-snake.svg
          dark_out_path: github-contribution-snake/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      - name: Commit snake files to main branch
        run: |
          git config user.name qgeng1465
          git config user.email qgeng1465@users.noreply.github.com
          git add github-contribution-snake/
          git commit -m "Update snake animation"
          git push
