name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # run daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        with:
          github_user_name: qgeng1465
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            # output: github-contribution-grid-snake.svg and github-contribution-grid-snake-dark.svg?palette=github-dark
          
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          user_name: qgeng1465
          user_email: qgeng1465@users.noreply.github.com
          commit_message: "Update snake animation"
